### ISSUE TITLE
Web browser XSS protection

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#105]
ZAP test alert:
- Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server
- Solution: Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'.

**Comment by cameronwolf** [comment]
Header is being properly set in newer browsers, this has been tested in chrome. Looking at the helmet documentation,(https://helmetjs.github.io/docs/xss-filter/), helmet will disable this header for older versions of internet explorer in order to prevent even worse security vulnerabilities from being exploited.
