### ISSUE TITLE
Check if requiredFields can be a local variable

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#259]
from [Sprint 4 Review](https://github.com/18F/fs-middlelayer-api/pull/9): 

> change to let requiredFields = [];

**Comment by cameronwolf** [comment]
The first line in the handlingMissingError function, where this comment was made, must not be a local variable in order to have ALL missing fields reported correctly. If it is local, missing a field like applicantInfo will only report that applicantInfo is missing, rather than reporting that applicantInfo, applicantInfo/firstName, etc. is missing.
